In [ ]:
vertical and horizontal - vstack and hstack 
code to take two arrays a and b, integrate a and b vertically and horizontzlly

In [7]:
import numpy as np
a = list(map(int, input("Enter 3 numbers for array a, space seperated: ").split()))
b = list(map(int, input("Enter 3 numbers for array b, space seperated: ").split()))
a = np.array(a)
b = np.array(b)
print("\n Vertical stack : \n", np.vstack((a,b)))
print("\n Horizontal stack : \n", np.hstack((a,b)))
v = np.vstack((a,b))
print("\nElement 5 access : ",v[1,1])
print("\nElement 5 access : ",v[1][1])

Enter 3 numbers for array a, space seperated:  1 3 5
Enter 3 numbers for array b, space seperated:  7 9 11



 Vertical stack : 
 [[ 1  3  5]
 [ 7  9 11]]

 Horizontal stack : 
 [ 1  3  5  7  9 11]

Element 5 access :  9

Element 5 access :  9


In [ ]:
code to extract all the odd numbers from user input and print them in a list using array of numpy
input : 1 2 3 4 5 9 8 7 6
output : [1,3,5,9,7]

In [17]:
arr = np.array(list(map(int, input("Enter numbers with space seperated : ").split())))
odd_nums = arr[arr%2 != 0]
print("Odd numbers list : ", odd_nums)

Enter numbers with space seperated :  1 2 3 4 5 9 8 7 6


Odd numbers list :  [1 3 5 9 7]


In [ ]:
input : 1 2 3 4 5 
output : [-1, 2, -1, 4, -1]

In [25]:
arr = np.array(list(map(int, input("Enter numbers with space seperated : ").split())))
arr[arr%2 != 0] = -1
print("List : ", arr)

Enter numbers with space seperated :  1 2 3 4 5 


List :  [-1  2 -1  4 -1]


In [ ]:
input : 1 2 3 4 5 
output : [True, 2, True, 4, True]

In [39]:
arr = np.array(list(map(int, input("Enter numbers with space seperated : ").split())), dtype = object)
arr[arr%2 != 0] = True
print("List : ", arr)

Enter numbers with space seperated :  1 2 3 4 5 


List :  [True 2 True 4 True]


In [ ]:
input : 1 2 3 4 5 
output : [1, 'even', 3, 'even', 5]

In [49]:
arr = np.array(list(map(int, input("Enter numbers with space seperated : ").split())), dtype = object)
arr[arr%2 == 0] = 'even'
print("List : ", arr)

Enter numbers with space seperated :  1 2 3 4 5 


List :  [1 'even' 3 'even' 5]


In [ ]:
input : 2 3 5 6 7
output : [False, True, False, True, False]
multiples of 3 should be given True remaining elements False

In [57]:
arr = np.array(list(map(int, input("Enter numbers with space seperated : ").split())))
mask = arr%3 == 0
print("List : ", mask)

Enter numbers with space seperated :  2 3 5 6 7


List :  [False  True False  True False]


In [81]:
arr=np.array([[1,2,3], [4,5,6]])
print("2-D Array : \n",arr)
print("Element at [1,1] : ", arr[1,1])
print("First row : ", arr[0, :])
print("First row first element sliced : \n", arr[:, 1:])
arr[0,0] = 100
print("Modify : \n", arr)

2-D Array : 
 [[1 2 3]
 [4 5 6]]
Element at [1,1] :  5
First row :  [1 2 3]
First row first element sliced : 
 [[2 3]
 [5 6]]
Modify : 
 [[100   2   3]
 [  4   5   6]]


In [85]:
arr = np.array([1,2,3, np.nan, 5])
print("Mean Ignoring NaN:", np.nanmean(arr)) 
print("Sum:", np.sum(arr))
# Sqrt1.N Ei = 1 to N(x~i=u)**2
print("std Ignoring NaN:", np.std(arr[~np.isnan(arr)]))

Mean Ignoring NaN: 2.75
Sum: nan
std Ignoring NaN: 1.479019945774904


In [87]:
arr = np.array ([1, np.nan, 3, 4, 5])
print("replace Nan with 0 : ", np.where(np.isnan(arr), 0, arr))

replace Nan with 0 :  [1. 0. 3. 4. 5.]


In [117]:
# universal functions ufuncs()

arr = np.array([1.5,2.9,9.8])
print(arr.astype(np.int32))

arr = np.array([1,2,3,4])
print(arr.astype(np.float64))

arr = np.array([1.5,2.9,9.8])
print(arr.astype(str))

arr = np.array([0, 1, 7, 0])
print(arr.astype(bool))

arr = np.array([True,True,False,True])
print(arr.astype(np.int32))

arr = np.array([1.5,2.9,9.8])
print(arr.astype(np.complex128))

arr = np.array([1,2,3,4])
print(arr.astype(np.int8))

arr = np.array([20250802, 10991224])
print(arr.astype('datetime64[D]'))

[1 2 9]
[1. 2. 3. 4.]
['1.5' '2.9' '9.8']
[False  True  True False]
[1 1 0 1]
[1.5+0.j 2.9+0.j 9.8+0.j]
[1 2 3 4]
['57414-10-25' '32062-12-13']
