In [ ]:
numpy
matrices - coordiunates location
math functions stastics / algebra

np.random.rand() - uniform random values
np.random.randn() - non uniform
np.dot - multiplication - matrices
np.arrange() - random range of values
np.array() - create/ delete/ access
np.zeros()/ np.ones() - creates an entire array with 0/1
np.mean()
np.std()
np.unique()
np.linalg.inv()

In [15]:
import numpy as np

x = np.array([1,2,3,4,5])
print("Array 1-D : \n", x)

Array 1-D : 
 [1 2 3 4 5]


In [17]:
y = np.array([[1,2],[3,4]])
print("Array 2-D : \n", y)

Array 2-D : 
 [[1 2]
 [3 4]]


In [19]:
o = np.ones((3,6))
print("ones : \n", o)

ones : 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [21]:
z = np.zeros((3,6))
print("zeros : \n", z)

zeros : 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [23]:
z = np.zeros((10,10))
print("zeros : \n", z)

zeros : 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
i = np.eye(10)
print("Identical Coordinates : \n",i)

Identical Coordinates : 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [27]:
r = np.arange(0,11,2)
print("Array : ", r)

Array :  [ 0  2  4  6  8 10]


In [33]:
seperate = np.linspace(0, 1, 5)
print("linspace : ", seperate)

linspace :  [0.   0.25 0.5  0.75 1.  ]


In [43]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print("Addition : ", a+b)
print("Product : ", a*b)
print("Square : ", a**2)
print("Sine Values : ",np.sin(a))
print("Mean : ", np.mean(a))
print("Max : ", np.max(a))

Addition :  [ 6  8 10 12]
Product :  [ 5 12 21 32]
Square :  [ 1  4  9 16]
Sine Values :  [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
Mean :  2.5
Max :  4


In [47]:
a = np.arange(1,10)
print(a)
reshaped = a.reshape((3,3))
print(reshaped)
linear = reshaped.reshape(-1)
print(linear)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [49]:
print("Element at (1,1):", reshaped[1,1])
linear = reshaped.flatten()
print(linear)

Element at (1,1): 5
[1 2 3 4 5 6 7 8 9]


In [51]:
print("Greater than 5 : ",linear[linear>5])

Greater than 5 :  [6 7 8 9]


In [53]:
print("Lesser than 5 : ",linear[linear<5])

Lesser than 5 :  [1 2 3 4]


In [68]:
print("Randon Numbers between 0 to 3 : ", np.random.rand(3))

Randon Numbers between 0 to 3 :  [0.14268949 0.79562453 0.1146846 ]


In [110]:
print("Random Integer : \n", np.random.randint(1, 100))

Random Integer : 
 73


In [114]:
print("Random Integer : \n", np.random.randint(1, 100, (2,3)))

Random Integer : 
 [[54 90 93]
 [20 30 45]]


In [120]:
print("Random Integer : \n", np.random.randint(1, 100, (3,3)))

Random Integer : 
 [[30 33 93]
 [13 85 99]
 [63 31 83]]


In [ ]:
Code to print a 3x3 matrix which were filled with boolean value True using numpy

In [122]:
arr = np.full((3,3), True)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [124]:
arr = np.full((3,3), dtype = bool)
print(arr)

TypeError: full() missing 1 required positional argument: 'fill_value'